vln = {'Burned_area':'Burned area [% yr-1]',
       'Pct_high_severity_3500':'High severity fire [% of fire months > 3500 kW m-1]',
       'Pct_high_severity_1700':'High severity fire [% of fire months > 1700 kW m-1]',
       'Pct_high_severity_1025':'High severity fire [% of fire months > 1025 kW m-1]',
       'Pct_high_severity_2600':'High severity fire /n [% of fire months > 2600 kW m-1]',
       'AWFI':'Area-weighted fire intensity [kW m-1]',
       'AGCD':'Above-ground carbon density [Kg C m-2]',
       'BA_conifer':'Conifer basal area (dbh > 10 cm) [m-2 ha-1]',
       'Pct_shrub_cover_canopy':'Shrub cover in canopy [%]',
       'Pct_shrub_cover':'Shrub cover [%]',
       'VCD':'Vegetation carbon density [Kg C m-2]',
       'Pct_conifer_cover_canopy':'Conifer cover [%]',
       'Pct_oak_cover_canopy':'Oak cover [%]',
       'Pct_pine_cover_canopy':'Pine cover [%]',
       'Pct_cedar_cover_canopy':'Cedar cover [%]',
       'Pct_fir_cover_canopy':'Fir cover [%]',
       'BA_pine':'Pine basal area (dbh > 10 cm) [m-2 ha-1]',
       'BA_cedar':'Cedar basal area (dbh > 10 cm) [m-2 ha-1]',
       'BA_fir':'Fir basal area (dbh > 10 cm) [m-2 ha-1]',
       'BA_oak':'Oak  basal area (dbh > 10 cm) [m-2 ha-1]',
       'TreeStemD':'Tree Stem Density [N ha-1] (> 10 cm dbh)',
       'Combustible_fuel':'Combustible fuel [Kg C m-2]',
       'NPP':'NPP',
       'mort_pine_fire_per_cap':'Pine fire mort [per capita (%) yr-1]',
       'mort_pine_cstarve_per_cap':'Pine cstarve mort [per capita (%) yr-1]',
       'mort_pine_hydr_per_cap':'Pine hydr failure mort [per capita (%) yr-1]',
       'mort_cedar_fire_per_cap':'Cedar fire mort [per capita (%) yr-1]',
       'mort_cedar_cstarve_per_cap':'Cedar cstarve mort [per capita (%) yr-1]',
       'mort_cedar_hydr_per_cap':'Cedar hydr failure mort [per capita (%) yr-1]',
       'mort_fir_fire_per_cap':'Fir fire mort [per capita (%) yr-1]',
       'mort_fir_cstarve_per_cap':'Fir cstarve mort [per capita (%) yr-1]',
       'mort_fir_hydr_per_cap':'Fir hydr failure mort [per capita (%) yr-1]',
       'mort_shrub_fire_per_cap':'Shrub fire mort [per capita (%) yr-1]',
       'mort_shrub_cstarve_per_cap':'Shrub cstarve mort [per capita (%) yr-1]',
       'mort_shrub_hydr_per_cap':'Shrub hydr failure mort [per capita (%) yr-1]',
       'mort_oak_fire_per_cap':'Oak fire mort [per capita (%) yr-1]',
       'mort_oak_cstarve_per_cap':'Oak cstarve mort [per capita (%) yr-1]',
       'mort_oak_hydr_per_cap':'Oak hydr failure mort [per capita month-1]',
       'SMP':'Soil matric potential [MPa 0.4 m depth]',
       'StemD10_pine':'Pine stem density [N ha-1] (> 10 cm dbh)',
       'mort_pine_fire_n_per_ha':'Pine fire mort [N ha-1 month-1]',
       'Rec_pine':'Recruitment pine [N ha-1 yr -1]',
       'Rec_cedar':'Recruitment cedar [N ha-1 yr -1]',
       'Rec_fir':'Recruitment fir [N ha-1 yr -1]',
       'Rec_shrub':'Recruitment shrub [N ha-1 yr -1]',
       'Rec_oak':'Recruitment oak [N ha-1 yr -1]'
       }
