---
title: "Parameter Sensitivity of Reproductive Allocation.Rmd"
author: "Adam Hanbury-Brown and Rachel Ward"
date: "August 2, 2021"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install Packages
```{r}
#install libraries
library(ncdf4)
library(tidyverse)
library(lubridate)
source('generalFunctions.R') #source the general functions in this repo
```


Set path to FATES output
```{r}
#set paths
data_path <- 'data/'
case_names <- c("repro_alloc_sensitivity.C63f3ea8a4-Fc1f6dddf.2021-08-03","repro_alloc_sensitivity_RA-0.4.C63f3ea8a4-Fc1f6dddf.2021-08-03")
case_aliases <- c("RA:0.1","RA:0.4")

getFilePaths <- function(base_data_path = data_path, case_name){
 path <- paste0(data_path,'/',case_name,'/')
 fileNames <- list.files(path,pattern = '.nc')
 files <- paste0(path,fileNames)
 return(files)
}
```

Define variables
```{r}
vars <- c('RECRUITMENT','DDBH_CANOPY_SCPF','DDBH_UNDERSTORY_SCPF','DDBH_SCPF','NPP_SCPF','PARPROF_DIR_CNLF','PARPROF_DIF_CNLF','PATCH_AREA_BY_AGE','NPATCH_BY_AGE','BA_SCPF', 'NPLANT_SCPF','AGB_SCPF')
```


Filter data by pft
```{r}
filterByPFT <- function(file = files[1],pft_int = 1,
                        map = "fates_pftmap_levscpf",
                        var='DDBH_CANOPY_SCPF'){
  
  mapVector <- ncvar_get(nc_open(file),varid = map)
  output <-  ncvar_get(nc_open(file),varid = var)[mapVector == pft_int]
  return(output)
  }
```

Get growth rates (cm per ind.) for the tropical tree PFT in the final timestep (at 10 yrs), dissaggregated by size class.
```{r}
n_size_classes = 13

growth_rates <- matrix(nrow = n_size_classes,ncol = length(case_names)) 
ind_per_ha <- matrix(nrow = n_size_classes,ncol = length(case_names))
agb <- matrix(nrow = n_size_classes,ncol = length(case_names))

for(c in 1:length(case_names)){
  files <- getFilePaths(case_name = case_names[c])
  lastTimeStep <- files[length(files)]
  
  growth_rates[,c] <- filterByPFT(file = lastTimeStep, var = 'DDBH_CANOPY_SCPF')
  ind_per_ha[,c] <- filterByPFT(file = lastTimeStep, var = 'NPLANT_SCPF')
  agb[,c] <- filterByPFT(file = lastTimeStep, var = 'AGB_SCPF')
  
}

size_class_lower_bounds_cm <- ncvar_get(nc_open(getFilePaths(case_name = case_names[1])),varid = 'fates_levscls')
growth_rates_cm_perInd_perYr <- cbind(growth_rates / ind_per_ha, size_class_lower_bounds_cm)
agb <- cbind(agb, size_class_lower_bounds_cm)

colNames <- c(case_aliases,"size_class_lower_cm")

colnames(x = growth_rates_cm_perInd_perYr) <- colNames
colnames(x = agb) <- colNames

print("growth rates (cm per ind. per year) by size class")
print(growth_rates_cm_perInd_perYr)
print("AGB (kg per m2) by size class")
print(agb) #kg C m2-1
```

Summary stats
```{r}
percent_change <- function(start,end){
  pc <- (end - start) / start
  return(na.omit(pc))
}

growth_rate_change <- percent_change(growth_rates_cm_perInd_perYr[,1], growth_rates_cm_perInd_perYr[,2])
agb_change <- percent_change(agb[,1], agb[,2])

print(paste("increasing RA from 0.1 to 0.4 results in a reduction of", as.numeric(growth_rate_change), "in growth rates (cm of dbh per ind.) at year 10"))
print(paste("increasing RA from 0.1 to 0.4 results in a reduction of", as.numeric(agb_change), "in AGB (kg per m2) at year 10"))
```




